apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-kubernetes
        visualize: "true"
    spec:
      containers:
        - name: hello-world-pod
          image: al3x3i/hello-kubernetes
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: hello-kubernetes-service
spec:
  selector:
    app: hello-kubernetes
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP